[de]
    languageCode = "de-de"
    languageName = "Deutsch"
    weight = 10
    title = "Datenanfragen.de"
    copyright = "Sofern nicht anders angegeben, ist dieses Werk unter einer Creative Commons Attribution 4.0 International-Lizenz lizensiert."
[en]
    languageCode = "en-us"
    languageName = "English"
    weight = 20
    title = "datarequests.org"
    copyright = "Except where otherwise noted, this work is licensed under a Creative Commons Attribution 4.0 International License."
