cache:
  paths:
  - node_modules/

variables:
  HUGO_VERSION: '0.46'
  HUGO_BINARY: hugo_${HUGO_VERSION}_linux-64bit

build:
  stage: build
  image: node:10-alpine
  before_script:
    - apk update
    - apk add bash git wget py-pygments
    - rm -rf /var/cache/apk/*
    - mkdir /usr/local/hugo
    - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_BINARY}.tar.gz -O /usr/local/hugo/${HUGO_BINARY}.tar.gz
    - tar xzf /usr/local/hugo/${HUGO_BINARY}.tar.gz -C /usr/local/hugo/
    - ln -s /usr/local/hugo/hugo /usr/local/bin/hugo
    - rm /usr/local/hugo/${HUGO_BINARY}.tar.gz
    - rm -rf /tmp/* /var/cache/apk/*
  script:
    - yarn
    - export DEPLOY_PRIME_URL="http://localhost:8080"
    - chmod +x deploy-branch.sh
    - ./deploy-branch.sh
  artifacts:
    paths:
      - public/

test:
  image: node:10-alpine
  stage: test
  dependencies:
    - build
  script:
    - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories
    - apk update
    - apk add libexif udev chromium chromium-chromedriver xvfb dbus-x11 ttf-freefont firefox
    - export CHROME_BIN=/usr/bin/chromium-browser
    - export CHROME_PATH=/usr/lib/chromium/
    - rm -rf /var/cache/apk/*
    - yarn global add geckodriver
    - yarn http-server ./public -s &
    - yarn test
    - exit 0