[build]
publish = "public"
command = "./deploy.sh"

[context.production.environment]
HUGO_VERSION = "0.46"
YARN_VERSION = "1.9.4"

# Netlify branch deploys only get a single subdomain which doesn't work with the production i18n Hugo config
[context.branch-deploy]
command = "./deploy-branch.sh"

[context.branch-deploy.environment]
HUGO_VERSION = "0.46"
YARN_VERSION = "1.9.4"