[[footerleft]]
    name = "Générateur de demande"
    url = "/generator"
    weight = 10
[[footerleft]]
    name = "Mes demandes"
    url = "/my-requests"
    weight = 20
[[footerleft]]
    name = "Mes données sauvegardées"
    url = "/id-data-controls"
    weight = 25
    post = "<br>"
[[footerleft]]
    name = "Base de données d'entreprises"
    url = "/company"
    weight = 30
# [[footerleft]]
#     name = "Articles"
#     url = "/blog"
#     weight = 40

# [[footercenter]]
#     name = "Fonctionnalités"
#     url = "#"
#     weight = 10
# [[footercenter]]
#     name = "Questions et réponses"
#     url = "#"
#     weight = 20
[[footercenter]]
    name = "Contribuer"
    url = "/contribute"
    weight = 30
[[footercenter]]
    name = "Faire un don"
    url = "https://www.datarequests.org/donate"
    weight = 40
    post = "<br>"
# [[footercenter]]
#     name = "Tes droits RGPD"
#     url = "/blog/deine-dsgvo-rechte"
#     weight = 50
[[footercenter]]
    name = "Modèles de lettres"
    url = "/sample-letters"
    weight = 60
# [[footercenter]]
#     name = "Autorités de contrôle"
#     url = "/supervisory-authorities"
#     weight = 70

[[footerright]]
    name = "Mentions légales"
    url = "/contact"
    weight = 10
[[footerright]]
    name = "Politique de confidentialité"
    url = "https://www.datarequests.org/privacy"
    weight = 20
[[footerright]]
    name = "Paramètres de confidentialité"
    url = "/privacy-controls"
    weight = 30
    post = "<br>"
[[footerright]]
    name = "Open Source"
    url = "/open-source"
    weight = 40
