[[footerleft]]
    name = "Anfrage generieren"
    url = "/generator"
    weight = 10
[[footerleft]]
    name = "Meine Anfragen"
    url = "/my-requests"
    weight = 20
[[footerleft]]
    name = "Meine gespeicherten Daten"
    url = "/id-data-controls"
    weight = 25
    post = "<br>"
[[footerleft]]
    name = "Unternehmensdatenbank"
    url = "/company"
    weight = 30
[[footerleft]]
    name = "Artikel"
    url = "/blog"
    weight = 40

# [[footercenter]]
#     name = "Features"
#     url = "#"
#     weight = 10
# [[footercenter]]
#     name = "Fragen und Antworten"
#     url = "#"
#     weight = 20
[[footercenter]]
    name = "Mitmachen"
    url = "/contribute"
    weight = 30
[[footercenter]]
    name = "Spenden"
    url = "https://verein.datenanfragen.de/spenden"
    weight = 40
    post = "<br>"
[[footercenter]]
    name = "Deine DSGVO-Rechte"
    url = "/blog/deine-dsgvo-rechte"
    weight = 50
[[footercenter]]
    name = "Musterschreiben"
    url = "/sample-letters"
    weight = 60
[[footercenter]]
    name = "Aufsichtsbehörden"
    url = "/datenschutz-aufsichtsbehoerden"
    weight = 70

[[footerright]]
    name = "Impressum"
    url = "/contact"
    weight = 10
[[footerright]]
    name = "Datenschutzerklärung"
    url = "https://verein.datenanfragen.de/datenschutz"
    weight = 20
[[footerright]]
    name = "Datenschutzeinstellungen"
    url = "/privacy-controls"
    weight = 30
    post = "<br>"
[[footerright]]
    name = "Open Source"
    url = "/open-source"
    weight = 40
